In [17]:
a = {'a':1,'b':2,'c':3}
if 'a' in a:
    print("yes")
    
if 'a' in a.keys():
    print('yes2')
    
print(a.keys())

print(a.items())

yes
yes2
dict_keys(['a', 'b', 'c'])
dict_items([('a', 1), ('b', 2), ('c', 3)])


In [18]:
print(a)
a.update({'d':123,'e':456,'f':789})
print(a)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 123, 'e': 456, 'f': 789}


In [22]:
for x in a.items():
    print(type(x))
    print(x[0],":",x[1])

<class 'tuple'>
a : 1
<class 'tuple'>
b : 2
<class 'tuple'>
c : 3
<class 'tuple'>
d : 123
<class 'tuple'>
e : 456
<class 'tuple'>
f : 789


In [19]:
print(a.get('c'))
print(a.get('c',234567))
print(a.get('g'))
print(a.get('g',9876))

3
3
None
9876


In [23]:
import pandas as pd

In [28]:
df = pd.read_csv('../data/surnames/surnames_with_splits.csv')

print(df.head())

print(df.iloc[1])

  nationality  nationality_index  split   surname
0      Arabic                 15  train     Totah
1      Arabic                 15  train    Abboud
2      Arabic                 15  train  Fakhoury
3      Arabic                 15  train     Srour
4      Arabic                 15  train    Sayegh
nationality          Arabic
nationality_index        15
split                 train
surname              Abboud
Name: 1, dtype: object


In [12]:
class Test(object):
    def __init__(self):
        print("init")
        self.a = [1,3,34,4,5,6,76,7,8,9]
        
    def __str__(self):
        return "%d" % len(self)
    
    def __len__(self):
        return len(self.a)

In [13]:
a = Test()

init


In [14]:
a.__str__

<bound method Test.__str__ of <__main__.Test object at 0x0000018C12B802B0>>

In [15]:
print(a)

10


In [42]:
import numpy as np
import torch

hiddens = []
for x in range(5):
    hiddens.append(torch.ones(5) * x)

print(hiddens)

#hiddens = torch.from_numpy(hiddens)
hiddens = torch.stack(hiddens)

print(hiddens)

[tensor([0., 0., 0., 0., 0.]), tensor([1., 1., 1., 1., 1.]), tensor([2., 2., 2., 2., 2.]), tensor([3., 3., 3., 3., 3.]), tensor([4., 4., 4., 4., 4.])]
tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.]])


In [43]:
print(hiddens.size())

hiddens = torch.unsqueeze(hiddens,0)
print(hiddens.size())
print(hiddens)
hiddens = hiddens.permute(1, 0, 2)

print(hiddens.size())
print(hiddens)

torch.Size([5, 5])
torch.Size([1, 5, 5])
tensor([[[0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]]])
torch.Size([5, 1, 5])
tensor([[[0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.]],

        [[4., 4., 4., 4., 4.]]])
